package com.example.acae30.modelos

data class Inventario (
    var Id:Int?,
    var Codigo:String?,
    var Tipo:String?,
    var Id_linea:Int?,
    var linea:String?,
    var descripcion:String?,
    var Unidad_medida:String,
    var Fraccion:Float?,
    var Nombre_fraccion:String?,
    var Existencia:Int?,
    var Costo:Float?,
    var costo_iva:Float?,
    var Precio_oferta:Float?,
    var Precio_iva:Float?,
    var Precio:Float?,
    var Precio_u:Float?,
    var Precio_u_iva:Float?,
    var Status:String?,
    var Fecha_inventario:String?,
    var Id_productor:Int?,
    var Productor:String?,
    var Id_proveedor:Int?,
    var Proveedor:String?,
    var Cesc:String?,
    var Combustible:String?,
    var Imagen:String?,
    var Rubro:String?,
    var Marca:String?,
    var Id_sublinea:Int?,
    var Sub_linea:String?,
    var Desc_autotamtico:Float?,
    var Bonificado: Double?,
    var Id_rubro:Int?,
    var Existencia_u:Float
)